# Generated by Django 2.0.6 on 2018-06-13 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details_url', models.URLField()),
                ('thumbnail_url', models.URLField()),
                ('duration', models.CharField(max_length=50)),
                ('days_showing', models.CharField(max_length=50)),
                ('time_showing', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_url', models.URLField()),
                ('thumbnail_url', models.URLField()),
                ('synopsis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='actors',
            field=models.ManyToManyField(related_name='movie_actors', to='scraper.Person'),
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='directors',
            field=models.ManyToManyField(related_name='movie_directors', to='scraper.Person'),
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_details', to='scraper.Movie'),
        ),
    ]
