# Generated by Django 2.0.6 on 2018-06-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='synopsis',
            field=models.TextField(null=True),
        ),
    ]
