# Generated by Django 2.0.6 on 2018-06-28 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20180628_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesShowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_showing', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times_showing', to='scraper.Movie')),
            ],
        ),
    ]
