# Generated by Django 2.0.6 on 2018-06-29 21:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_timesshowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesshowing',
            name='time_showing',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 29, 21, 10, 23, 14251, tzinfo=utc)),
        ),
    ]
